export const categories = {
  'Layout': ['appstore', 'reorder', 'accordion', 'tabs', 'glass'],
  'Scroll': ['parallax', 'heroparallax', 'hscroll', 'scrollprogress', 'velocity'],
  'Text': ['scramble', 'reveal', 'flip', 'typewriter', 'splittext', 'wordpullup', 'wavy'],
  'Interaction': ['magnetic', 'cursor', 'stack', 'gesture2', 'fab', 'dock'],
  'Effects': ['aurora', 'particles', 'pathdraw', 'blurfade', 'clippath'],
  '3D': ['3dcard', 'flipcard3d', 'cube3d', 'book3d', 'carousel3d', 'layered3d', 'button3d', 'tiltgallery3d', 'floating3d', 'door3d'],
  'UI': ['notifications', 'skeleton', 'counter', 'progress', 'bento', 'shimmer', 'ripple'],
  'Advanced': ['stagger', 'marquee', 'imagegrid'],
  'Pro': ['borderbeam', 'spotlight', 'gradientfollow', 'textgenerate', 'orbit'],
  'Premium': ['meteors', 'pulserings', 'holographic', 'breathing', 'unfold', 'gradienttext', 'typingcursor'],
  'Premium+': ['auroraborealis', 'fireworks', 'dnahelix', 'starfield', 'matrixrain', 'lightning'],
  'Heroes': ['herosplit', 'herocentered', 'herostats', 'herocards', 'herogradient', 'heromarquee', 'herointeractive', 'heroproduct', 'herobadge'],
  'Components': ['featuregrid', 'pricing', 'testimonials', 'cta', 'logocloud', 'faq', 'newsletter', 'footer'],
  'Landing+': ['bentogrid', 'testimonialwall', 'featureshowcase', 'socialproof', 'comparisontable', 'timeline', 'teamgrid', 'statscounter', 'featuretabs'],
  'Stock Market': ['stockticker', 'candlestick', 'stockcard', 'portfoliopie', 'orderbook', 'tradingpanel', 'marketheatmap', 'watchlist', 'pricealert', 'marketoverview'],
  'Voice Chat': ['voicechatwidget', 'audiowaveform', 'livetranscription', 'callstatus', 'voiceorb', 'voiceorbnebula', 'audiospectrum', 'voiceactivity', 'conversationhistory', 'audiocontrols'],
  'Analytics': ['linechart', 'barchart', 'areachart', 'donutchart', 'radarchart', 'scatterplot', 'progresschart', 'livegauge', 'histogram', 'multilinechart'],
  'Utilities': ['weatherwidget', 'calendarwidget', 'timerwidget', 'stopwatchwidget', 'calculatorwidget'],
  'Media': ['musicplayer', 'photogallery', 'todolist', 'notesapp', 'contactslist'],
  'Widgets': ['digitalclock', 'alarmclock', 'countdown', 'pomodoro'],
  'Development': ['codeeditor', 'filemanager', 'settingspanel', 'userprofile', 'searchbar'],
  'Communication': ['chatinterface', 'emailclient', 'eventcalendar', 'kanbanboard', 'ganttchart'],
  'Data Display': ['datatabls', 'timelineview', 'badgegrid', 'statsdashboard', 'feedstream'],
  'Navigation': ['breadcrumbnav', 'sidemenu', 'tabbar', 'megamenu', 'pagination'],
  'Entertainment': ['gamecard', 'moviecard', 'podcastplayer'],
  'Technology': ['serverstatus', 'apidocs', 'codesnippet', 'terminal', 'databaseview'],
  'Lifestyle': ['fitnesstracker', 'expensetracker', 'travelplanner', 'recipecard', 'scoreboard'],
  'Workflow Automation': ['workflowbuilder', 'automationtrigger', 'workflowtimeline', 'workflowsteps', 'conditionbuilder', 'actionlibrary', 'workflowtemplate', 'executionhistory', 'workflowvariables', 'integrationpanel', 'workflowscheduler', 'datamapper', 'errorhandling', 'workflowversions', 'notificationcenter', 'workflowmetrics', 'approvalflow', 'webhooktester', 'logviewer', 'workflowdebugger', 'nodecanvas', 'nodepalette', 'nodeinspector', 'nodeminimap', 'nodeconnections', 'nodegrouping', 'nodetemplates', 'nodeexecution', 'nodesearch', 'nodevalidation'],
};
