// Auto-generated by extract-components.js
import AppStoreDemo from '../components/demos/AppStoreDemo';
import ReorderDemo from '../components/demos/ReorderDemo';
import AccordionDemo from '../components/demos/AccordionDemo';
import TabsDemo from '../components/demos/TabsDemo';
import ParallaxDemo from '../components/demos/ParallaxDemo';
import HeroParallaxDemo from '../components/demos/HeroParallaxDemo';
import HScrollDemo from '../components/demos/HScrollDemo';
import ScrollProgressDemo from '../components/demos/ScrollProgressDemo';
import ScrambleDemo from '../components/demos/ScrambleDemo';
import RevealDemo from '../components/demos/RevealDemo';
import FlipDemo from '../components/demos/FlipDemo';
import TypewriterDemo from '../components/demos/TypewriterDemo';
import SplitTextDemo from '../components/demos/SplitTextDemo';
import MagneticDemo from '../components/demos/MagneticDemo';
import CursorDemo from '../components/demos/CursorDemo';
import StackDemo from '../components/demos/StackDemo';
import Gesture2Demo from '../components/demos/Gesture2Demo';
import FabDemo from '../components/demos/FabDemo';
import AuroraDemo from '../components/demos/AuroraDemo';
import ParticlesDemo from '../components/demos/ParticlesDemo';
import PathDrawDemo from '../components/demos/PathDrawDemo';
import Card3DDemo from '../components/demos/Card3DDemo';
import FlipCard3DDemo from '../components/demos/FlipCard3DDemo';
import Cube3DDemo from '../components/demos/Cube3DDemo';
import Book3DDemo from '../components/demos/Book3DDemo';
import Carousel3DDemo from '../components/demos/Carousel3DDemo';
import LayeredStack3DDemo from '../components/demos/LayeredStack3DDemo';
import Button3DDemo from '../components/demos/Button3DDemo';
import TiltGallery3DDemo from '../components/demos/TiltGallery3DDemo';
import Floating3DDemo from '../components/demos/Floating3DDemo';
import Door3DDemo from '../components/demos/Door3DDemo';
import NotificationsDemo from '../components/demos/NotificationsDemo';
import SkeletonDemo from '../components/demos/SkeletonDemo';
import CounterDemo from '../components/demos/CounterDemo';
import ProgressDemo from '../components/demos/ProgressDemo';
import StaggerDemo from '../components/demos/StaggerDemo';
import MarqueeDemo from '../components/demos/MarqueeDemo';
import ImageGridDemo from '../components/demos/ImageGridDemo';
import BlurFadeDemo from '../components/demos/BlurFadeDemo';
import DockDemo from '../components/demos/DockDemo';
import WordPullUpDemo from '../components/demos/WordPullUpDemo';
import WavyTextDemo from '../components/demos/WavyTextDemo';
import VelocityScrollDemo from '../components/demos/VelocityScrollDemo';
import ClipPathDemo from '../components/demos/ClipPathDemo';
import GlassDemo from '../components/demos/GlassDemo';
import BorderBeamDemo from '../components/demos/BorderBeamDemo';
import SpotlightCardDemo from '../components/demos/SpotlightCardDemo';
import ShimmerButtonDemo from '../components/demos/ShimmerButtonDemo';
import GradientFollowDemo from '../components/demos/GradientFollowDemo';
import RippleDemo from '../components/demos/RippleDemo';
import BentoDemo from '../components/demos/BentoDemo';
import TextGenerateDemo from '../components/demos/TextGenerateDemo';
import OrbitDemo from '../components/demos/OrbitDemo';
import MeteorsDemo from '../components/demos/MeteorsDemo';
import PulseRingsDemo from '../components/demos/PulseRingsDemo';
import HolographicDemo from '../components/demos/HolographicDemo';
import BreathingDemo from '../components/demos/BreathingDemo';
import UnfoldDemo from '../components/demos/UnfoldDemo';
import GradientTextDemo from '../components/demos/GradientTextDemo';
import TypingCursorDemo from '../components/demos/TypingCursorDemo';
import AuroraBorealisDemo from '../components/demos/AuroraBorealisDemo';
import FireworksDemo from '../components/demos/FireworksDemo';
import DNAHelixDemo from '../components/demos/DNAHelixDemo';
import StarFieldDemo from '../components/demos/StarFieldDemo';
import MatrixRainDemo from '../components/demos/MatrixRainDemo';
import LightningDemo from '../components/demos/LightningDemo';
import HeroSplitDemo from '../components/demos/HeroSplitDemo';
import HeroCenteredDemo from '../components/demos/HeroCenteredDemo';
import HeroStatsDemo from '../components/demos/HeroStatsDemo';
import HeroCardsDemo from '../components/demos/HeroCardsDemo';
import HeroGradientDemo from '../components/demos/HeroGradientDemo';
import HeroMarqueeDemo from '../components/demos/HeroMarqueeDemo';
import HeroInteractiveDemo from '../components/demos/HeroInteractiveDemo';
import HeroProductDemo from '../components/demos/HeroProductDemo';
import HeroBadgeDemo from '../components/demos/HeroBadgeDemo';
import FeatureGridDemo from '../components/demos/FeatureGridDemo';
import PricingDemo from '../components/demos/PricingDemo';
import TestimonialsDemo from '../components/demos/TestimonialsDemo';
import CTADemo from '../components/demos/CTADemo';
import LogoCloudDemo from '../components/demos/LogoCloudDemo';
import FAQDemo from '../components/demos/FAQDemo';
import NewsletterDemo from '../components/demos/NewsletterDemo';
import FooterDemo from '../components/demos/FooterDemo';
import BentoGridDemo from '../components/demos/BentoGridDemo';
import TestimonialWallDemo from '../components/demos/TestimonialWallDemo';
import FeatureShowcaseDemo from '../components/demos/FeatureShowcaseDemo';
import SocialProofDemo from '../components/demos/SocialProofDemo';
import ComparisonTableDemo from '../components/demos/ComparisonTableDemo';
import TimelineDemo from '../components/demos/TimelineDemo';
import TeamGridDemo from '../components/demos/TeamGridDemo';
import StatsCounterDemo from '../components/demos/StatsCounterDemo';
import FeatureTabsDemo from '../components/demos/FeatureTabsDemo';
import StockTickerDemo from '../components/demos/StockTickerDemo';
import CandlestickDemo from '../components/demos/CandlestickDemo';
import StockCardDemo from '../components/demos/StockCardDemo';
import PortfolioPieDemo from '../components/demos/PortfolioPieDemo';
import OrderBookDemo from '../components/demos/OrderBookDemo';
import TradingPanelDemo from '../components/demos/TradingPanelDemo';
import MarketHeatmapDemo from '../components/demos/MarketHeatmapDemo';
import WatchlistDemo from '../components/demos/WatchlistDemo';
import PriceAlertDemo from '../components/demos/PriceAlertDemo';
import MarketOverviewDemo from '../components/demos/MarketOverviewDemo';
import VoiceChatWidgetDemo from '../components/demos/VoiceChatWidgetDemo';
import AudioWaveformDemo from '../components/demos/AudioWaveformDemo';
import LiveTranscriptionDemo from '../components/demos/LiveTranscriptionDemo';
import CallStatusDemo from '../components/demos/CallStatusDemo';
import VoiceOrbDemo from '../components/demos/VoiceOrbDemo';
import VoiceOrbNebulaDemo from '../components/demos/VoiceOrbNebulaDemo';
import AudioSpectrumDemo from '../components/demos/AudioSpectrumDemo';
import VoiceActivityDemo from '../components/demos/VoiceActivityDemo';
import ConversationHistoryDemo from '../components/demos/ConversationHistoryDemo';
import AudioControlsDemo from '../components/demos/AudioControlsDemo';
import LineChartDemo from '../components/demos/LineChartDemo';
import BarChartDemo from '../components/demos/BarChartDemo';
import AreaChartDemo from '../components/demos/AreaChartDemo';
import DonutChartDemo from '../components/demos/DonutChartDemo';
import RadarChartDemo from '../components/demos/RadarChartDemo';
import ScatterPlotDemo from '../components/demos/ScatterPlotDemo';
import ProgressChartDemo from '../components/demos/ProgressChartDemo';
import LiveGaugeDemo from '../components/demos/LiveGaugeDemo';
import HistogramDemo from '../components/demos/HistogramDemo';
import MultiLineChartDemo from '../components/demos/MultiLineChartDemo';
import WeatherWidgetDemo from '../components/demos/WeatherWidgetDemo';
import CalendarWidgetDemo from '../components/demos/CalendarWidgetDemo';
import TimerWidgetDemo from '../components/demos/TimerWidgetDemo';
import CalculatorWidgetDemo from '../components/demos/CalculatorWidgetDemo';
import StopwatchWidgetDemo from '../components/demos/StopwatchWidgetDemo';
import MusicPlayerDemo from '../components/demos/MusicPlayerDemo';
import PhotoGalleryDemo from '../components/demos/PhotoGalleryDemo';
import TodoListDemo from '../components/demos/TodoListDemo';
import NotesAppDemo from '../components/demos/NotesAppDemo';
import ContactsListDemo from '../components/demos/ContactsListDemo';
import DigitalClockDemo from '../components/demos/DigitalClockDemo';
import AlarmClockDemo from '../components/demos/AlarmClockDemo';
import CountdownDemo from '../components/demos/CountdownDemo';
import PomodoroDemo from '../components/demos/PomodoroDemo';
import CodeEditorDemo from '../components/demos/CodeEditorDemo';
import FileManagerDemo from '../components/demos/FileManagerDemo';
import SettingsPanelDemo from '../components/demos/SettingsPanelDemo';
import UserProfileDemo from '../components/demos/UserProfileDemo';
import SearchBarDemo from '../components/demos/SearchBarDemo';
import ChatInterfaceDemo from '../components/demos/ChatInterfaceDemo';
import EmailClientDemo from '../components/demos/EmailClientDemo';
import EventCalendarDemo from '../components/demos/EventCalendarDemo';
import KanbanBoardDemo from '../components/demos/KanbanBoardDemo';
import BreadcrumbNavDemo from '../components/demos/BreadcrumbNavDemo';
import SideMenuDemo from '../components/demos/SideMenuDemo';
import TabBarDemo from '../components/demos/TabBarDemo';
import MegaMenuDemo from '../components/demos/MegaMenuDemo';
import PaginationDemo from '../components/demos/PaginationDemo';
import GanttChartDemo from '../components/demos/GanttChartDemo';
import DataTableDemo from '../components/demos/DataTableDemo';
import TimelineViewDemo from '../components/demos/TimelineViewDemo';
import BadgeGridDemo from '../components/demos/BadgeGridDemo';
import StatsDashboardDemo from '../components/demos/StatsDashboardDemo';
import FeedStreamDemo from '../components/demos/FeedStreamDemo';
import FormWizardDemo from '../components/demos/FormWizardDemo';
import SearchFilterDemo from '../components/demos/SearchFilterDemo';
import RatingInputDemo from '../components/demos/RatingInputDemo';
import UploadZoneDemo from '../components/demos/UploadZoneDemo';
import ToggleGroupDemo from '../components/demos/ToggleGroupDemo';
import ServerStatusDemo from '../components/demos/ServerStatusDemo';
import APIDocsDemo from '../components/demos/APIDocsDemo';
import CodeSnippetDemo from '../components/demos/CodeSnippetDemo';
import TerminalDemo from '../components/demos/TerminalDemo';
import DatabaseViewDemo from '../components/demos/DatabaseViewDemo';
import GameCardDemo from '../components/demos/GameCardDemo';
import MovieCardDemo from '../components/demos/MovieCardDemo';
import PodcastPlayerDemo from '../components/demos/PodcastPlayerDemo';
import ShoppingCartDemo from '../components/demos/ShoppingCartDemo';
import CommentSectionDemo from '../components/demos/CommentSectionDemo';
import UserCardDemo from '../components/demos/UserCardDemo';
import NotificationListDemo from '../components/demos/NotificationListDemo';
import ShareButtonsDemo from '../components/demos/ShareButtonsDemo';
import LeaderboardDemo from '../components/demos/LeaderboardDemo';
import CheckoutFormDemo from '../components/demos/CheckoutFormDemo';
import OrderTrackingDemo from '../components/demos/OrderTrackingDemo';
import ReviewCardDemo from '../components/demos/ReviewCardDemo';
import FitnessTrackerDemo from '../components/demos/FitnessTrackerDemo';
import ExpenseTrackerDemo from '../components/demos/ExpenseTrackerDemo';
import TravelPlannerDemo from '../components/demos/TravelPlannerDemo';
import RecipeCardDemo from '../components/demos/RecipeCardDemo';
import ScoreBoardDemo from '../components/demos/ScoreBoardDemo';
import WorkflowBuilderDemo from '../components/demos/WorkflowBuilderDemo';
import AutomationTriggerDemo from '../components/demos/AutomationTriggerDemo';
import WorkflowTimelineDemo from '../components/demos/WorkflowTimelineDemo';
import WorkflowStepsDemo from '../components/demos/WorkflowStepsDemo';
import ConditionBuilderDemo from '../components/demos/ConditionBuilderDemo';
import ActionLibraryDemo from '../components/demos/ActionLibraryDemo';
import WorkflowTemplateDemo from '../components/demos/WorkflowTemplateDemo';
import ExecutionHistoryDemo from '../components/demos/ExecutionHistoryDemo';
import WorkflowVariablesDemo from '../components/demos/WorkflowVariablesDemo';
import IntegrationPanelDemo from '../components/demos/IntegrationPanelDemo';
import WorkflowSchedulerDemo from '../components/demos/WorkflowSchedulerDemo';
import DataMapperDemo from '../components/demos/DataMapperDemo';
import ErrorHandlingDemo from '../components/demos/ErrorHandlingDemo';
import WorkflowVersionsDemo from '../components/demos/WorkflowVersionsDemo';
import NotificationCenterDemo from '../components/demos/NotificationCenterDemo';
import WorkflowMetricsDemo from '../components/demos/WorkflowMetricsDemo';
import ApprovalFlowDemo from '../components/demos/ApprovalFlowDemo';
import WebhookTesterDemo from '../components/demos/WebhookTesterDemo';
import LogViewerDemo from '../components/demos/LogViewerDemo';
import WorkflowDebuggerDemo from '../components/demos/WorkflowDebuggerDemo';
import NodeCanvasDemo from '../components/demos/NodeCanvasDemo';
import NodePaletteDemo from '../components/demos/NodePaletteDemo';
import NodeInspectorDemo from '../components/demos/NodeInspectorDemo';
import NodeMinimapDemo from '../components/demos/NodeMinimapDemo';
import NodeConnectionsDemo from '../components/demos/NodeConnectionsDemo';
import NodeGroupingDemo from '../components/demos/NodeGroupingDemo';
import NodeTemplatesDemo from '../components/demos/NodeTemplatesDemo';
import NodeExecutionDemo from '../components/demos/NodeExecutionDemo';
import NodeSearchDemo from '../components/demos/NodeSearchDemo';
import NodeValidationDemo from '../components/demos/NodeValidationDemo';

export const demoComponents = {
  'appstore': AppStoreDemo,
  'reorder': ReorderDemo,
  'accordion': AccordionDemo,
  'tabs': TabsDemo,
  'parallax': ParallaxDemo,
  'heroparallax': HeroParallaxDemo,
  'hscroll': HScrollDemo,
  'scrollprogress': ScrollProgressDemo,
  'scramble': ScrambleDemo,
  'reveal': RevealDemo,
  'flip': FlipDemo,
  'typewriter': TypewriterDemo,
  'splittext': SplitTextDemo,
  'magnetic': MagneticDemo,
  'cursor': CursorDemo,
  'stack': StackDemo,
  'gesture2': Gesture2Demo,
  'fab': FabDemo,
  'aurora': AuroraDemo,
  'particles': ParticlesDemo,
  'pathdraw': PathDrawDemo,
  'card3d': Card3DDemo,
  'flipcard3d': FlipCard3DDemo,
  'cube3d': Cube3DDemo,
  'book3d': Book3DDemo,
  'carousel3d': Carousel3DDemo,
  'layeredstack3d': LayeredStack3DDemo,
  'button3d': Button3DDemo,
  'tiltgallery3d': TiltGallery3DDemo,
  'floating3d': Floating3DDemo,
  'door3d': Door3DDemo,
  'notifications': NotificationsDemo,
  'skeleton': SkeletonDemo,
  'counter': CounterDemo,
  'progress': ProgressDemo,
  'stagger': StaggerDemo,
  'marquee': MarqueeDemo,
  'imagegrid': ImageGridDemo,
  'blurfade': BlurFadeDemo,
  'dock': DockDemo,
  'wordpullup': WordPullUpDemo,
  'wavytext': WavyTextDemo,
  'velocityscroll': VelocityScrollDemo,
  'clippath': ClipPathDemo,
  'glass': GlassDemo,
  'borderbeam': BorderBeamDemo,
  'spotlightcard': SpotlightCardDemo,
  'shimmerbutton': ShimmerButtonDemo,
  'gradientfollow': GradientFollowDemo,
  'ripple': RippleDemo,
  'bento': BentoDemo,
  'textgenerate': TextGenerateDemo,
  'orbit': OrbitDemo,
  'meteors': MeteorsDemo,
  'pulserings': PulseRingsDemo,
  'holographic': HolographicDemo,
  'breathing': BreathingDemo,
  'unfold': UnfoldDemo,
  'gradienttext': GradientTextDemo,
  'typingcursor': TypingCursorDemo,
  'auroraborealis': AuroraBorealisDemo,
  'fireworks': FireworksDemo,
  'dnahelix': DNAHelixDemo,
  'starfield': StarFieldDemo,
  'matrixrain': MatrixRainDemo,
  'lightning': LightningDemo,
  'herosplit': HeroSplitDemo,
  'herocentered': HeroCenteredDemo,
  'herostats': HeroStatsDemo,
  'herocards': HeroCardsDemo,
  'herogradient': HeroGradientDemo,
  'heromarquee': HeroMarqueeDemo,
  'herointeractive': HeroInteractiveDemo,
  'heroproduct': HeroProductDemo,
  'herobadge': HeroBadgeDemo,
  'featuregrid': FeatureGridDemo,
  'pricing': PricingDemo,
  'testimonials': TestimonialsDemo,
  'cta': CTADemo,
  'logocloud': LogoCloudDemo,
  'faq': FAQDemo,
  'newsletter': NewsletterDemo,
  'footer': FooterDemo,
  'bentogrid': BentoGridDemo,
  'testimonialwall': TestimonialWallDemo,
  'featureshowcase': FeatureShowcaseDemo,
  'socialproof': SocialProofDemo,
  'comparisontable': ComparisonTableDemo,
  'timeline': TimelineDemo,
  'teamgrid': TeamGridDemo,
  'statscounter': StatsCounterDemo,
  'featuretabs': FeatureTabsDemo,
  'stockticker': StockTickerDemo,
  'candlestick': CandlestickDemo,
  'stockcard': StockCardDemo,
  'portfoliopie': PortfolioPieDemo,
  'orderbook': OrderBookDemo,
  'tradingpanel': TradingPanelDemo,
  'marketheatmap': MarketHeatmapDemo,
  'watchlist': WatchlistDemo,
  'pricealert': PriceAlertDemo,
  'marketoverview': MarketOverviewDemo,
  'voicechatwidget': VoiceChatWidgetDemo,
  'audiowaveform': AudioWaveformDemo,
  'livetranscription': LiveTranscriptionDemo,
  'callstatus': CallStatusDemo,
  'voiceorb': VoiceOrbDemo,
  'voiceorbnebula': VoiceOrbNebulaDemo,
  'audiospectrum': AudioSpectrumDemo,
  'voiceactivity': VoiceActivityDemo,
  'conversationhistory': ConversationHistoryDemo,
  'audiocontrols': AudioControlsDemo,
  'linechart': LineChartDemo,
  'barchart': BarChartDemo,
  'areachart': AreaChartDemo,
  'donutchart': DonutChartDemo,
  'radarchart': RadarChartDemo,
  'scatterplot': ScatterPlotDemo,
  'progresschart': ProgressChartDemo,
  'livegauge': LiveGaugeDemo,
  'histogram': HistogramDemo,
  'multilinechart': MultiLineChartDemo,
  'weatherwidget': WeatherWidgetDemo,
  'calendarwidget': CalendarWidgetDemo,
  'timerwidget': TimerWidgetDemo,
  'calculatorwidget': CalculatorWidgetDemo,
  'stopwatchwidget': StopwatchWidgetDemo,
  'musicplayer': MusicPlayerDemo,
  'photogallery': PhotoGalleryDemo,
  'todolist': TodoListDemo,
  'notesapp': NotesAppDemo,
  'contactslist': ContactsListDemo,
  'digitalclock': DigitalClockDemo,
  'alarmclock': AlarmClockDemo,
  'countdown': CountdownDemo,
  'pomodoro': PomodoroDemo,
  'codeeditor': CodeEditorDemo,
  'filemanager': FileManagerDemo,
  'settingspanel': SettingsPanelDemo,
  'userprofile': UserProfileDemo,
  'searchbar': SearchBarDemo,
  'chatinterface': ChatInterfaceDemo,
  'emailclient': EmailClientDemo,
  'eventcalendar': EventCalendarDemo,
  'kanbanboard': KanbanBoardDemo,
  'breadcrumbnav': BreadcrumbNavDemo,
  'sidemenu': SideMenuDemo,
  'tabbar': TabBarDemo,
  'megamenu': MegaMenuDemo,
  'pagination': PaginationDemo,
  'ganttchart': GanttChartDemo,
  'datatable': DataTableDemo,
  'timelineview': TimelineViewDemo,
  'badgegrid': BadgeGridDemo,
  'statsdashboard': StatsDashboardDemo,
  'feedstream': FeedStreamDemo,
  'formwizard': FormWizardDemo,
  'searchfilter': SearchFilterDemo,
  'ratinginput': RatingInputDemo,
  'uploadzone': UploadZoneDemo,
  'togglegroup': ToggleGroupDemo,
  'serverstatus': ServerStatusDemo,
  'apidocs': APIDocsDemo,
  'codesnippet': CodeSnippetDemo,
  'terminal': TerminalDemo,
  'databaseview': DatabaseViewDemo,
  'gamecard': GameCardDemo,
  'moviecard': MovieCardDemo,
  'podcastplayer': PodcastPlayerDemo,
  'shoppingcart': ShoppingCartDemo,
  'commentsection': CommentSectionDemo,
  'usercard': UserCardDemo,
  'notificationlist': NotificationListDemo,
  'sharebuttons': ShareButtonsDemo,
  'leaderboard': LeaderboardDemo,
  'checkoutform': CheckoutFormDemo,
  'ordertracking': OrderTrackingDemo,
  'reviewcard': ReviewCardDemo,
  'fitnesstracker': FitnessTrackerDemo,
  'expensetracker': ExpenseTrackerDemo,
  'travelplanner': TravelPlannerDemo,
  'recipecard': RecipeCardDemo,
  'scoreboard': ScoreBoardDemo,
  'workflowbuilder': WorkflowBuilderDemo,
  'automationtrigger': AutomationTriggerDemo,
  'workflowtimeline': WorkflowTimelineDemo,
  'workflowsteps': WorkflowStepsDemo,
  'conditionbuilder': ConditionBuilderDemo,
  'actionlibrary': ActionLibraryDemo,
  'workflowtemplate': WorkflowTemplateDemo,
  'executionhistory': ExecutionHistoryDemo,
  'workflowvariables': WorkflowVariablesDemo,
  'integrationpanel': IntegrationPanelDemo,
  'workflowscheduler': WorkflowSchedulerDemo,
  'datamapper': DataMapperDemo,
  'errorhandling': ErrorHandlingDemo,
  'workflowversions': WorkflowVersionsDemo,
  'notificationcenter': NotificationCenterDemo,
  'workflowmetrics': WorkflowMetricsDemo,
  'approvalflow': ApprovalFlowDemo,
  'webhooktester': WebhookTesterDemo,
  'logviewer': LogViewerDemo,
  'workflowdebugger': WorkflowDebuggerDemo,
  'nodecanvas': NodeCanvasDemo,
  'nodepalette': NodePaletteDemo,
  'nodeinspector': NodeInspectorDemo,
  'nodeminimap': NodeMinimapDemo,
  'nodeconnections': NodeConnectionsDemo,
  'nodegrouping': NodeGroupingDemo,
  'nodetemplates': NodeTemplatesDemo,
  'nodeexecution': NodeExecutionDemo,
  'nodesearch': NodeSearchDemo,
  'nodevalidation': NodeValidationDemo,
};

export const demoIds = Object.keys(demoComponents);
