export const demoNames = {
  appstore: 'App Store',
  reorder: 'Reorder List',
  accordion: 'Accordion',
  tabs: 'Animated Tabs',
  parallax: 'Parallax Layers',
  heroparallax: 'Hero Parallax',
  hscroll: 'Horizontal Scroll',
  scrollprogress: 'Scroll Progress',
  scramble: 'Text Scramble',
  reveal: 'Text Reveal',
  flip: 'Flip Text',
  typewriter: 'Typewriter',
  splittext: 'Split Text',
  magnetic: 'Magnetic Button',
  cursor: 'Custom Cursor',
  stack: 'Card Stack',
  gesture2: 'Slide Unlock',
  fab: 'FAB Menu',
  aurora: 'Aurora Button',
  particles: 'Particle Trail',
  pathdraw: 'Path Drawing',
  '3dcard': '3D Card',
  notifications: 'Notifications',
  skeleton: 'Skeleton',
  counter: 'Counter',
  progress: 'Progress Ring',
  stagger: 'Stagger Grid',
  marquee: 'Marquee',
  imagegrid: 'Image Reveal',
  blurfade: 'Blur Fade',
  dock: 'macOS Dock',
  wordpullup: 'Word Pull Up',
  wavy: 'Wavy Text',
  velocity: 'Velocity Scroll',
  clippath: 'Clip Path',
  glass: 'Glass Cards',
  flipcard3d: '3D Flip Card',
  cube3d: '3D Cube',
  book3d: '3D Book',
  carousel3d: '3D Carousel',
  layered3d: '3D Layer Stack',
  button3d: '3D Button',
  tiltgallery3d: '3D Tilt Gallery',
  floating3d: '3D Floating',
  door3d: '3D Door',
  borderbeam: 'Border Beam',
  spotlight: 'Spotlight Cards',
  shimmer: 'Shimmer Button',
  gradientfollow: 'Gradient Follow',
  ripple: 'Ripple Effect',
  bento: 'Bento Grid',
  textgenerate: 'Text Generate',
  orbit: 'Orbit Animation',
  meteors: 'Meteors',
  pulserings: 'Pulse Rings',
  holographic: 'Holographic Card',
  breathing: 'Breathing Glow',
  unfold: 'Unfold Card',
  gradienttext: 'Gradient Text',
  typingcursor: 'Typing Cursor',
  auroraborealis: 'Aurora Borealis',
  fireworks: 'Fireworks',
  dnahelix: 'DNA Helix',
  starfield: 'Star Field',
  matrixrain: 'Matrix Rain',
  lightning: 'Lightning',
  herosplit: 'Hero Split',
  herocentered: 'Hero Centered',
  herostats: 'Hero Stats',
  herocards: 'Hero Cards',
  herogradient: 'Hero Gradient',
  heromarquee: 'Hero Marquee',
  herointeractive: 'Hero Interactive',
  heroproduct: 'Hero Product',
  herobadge: 'Hero Badge',
  featuregrid: 'Feature Grid',
  pricing: 'Pricing Cards',
  testimonials: 'Testimonials',
  cta: 'CTA Section',
  logocloud: 'Logo Cloud',
  faq: 'FAQ Accordion',
  newsletter: 'Newsletter',
  footer: 'Footer',
  bentogrid: 'Bento Grid',
  testimonialwall: 'Testimonial Wall',
  featureshowcase: 'Feature Showcase',
  socialproof: 'Social Proof',
  comparisontable: 'Comparison Table',
  timeline: 'Timeline',
  teamgrid: 'Team Grid',
  statscounter: 'Stats Counter',
  featuretabs: 'Feature Tabs',
  stockticker: 'Stock Ticker',
  candlestick: 'Candlestick Chart',
  stockcard: 'Stock Card',
  portfoliopie: 'Portfolio Pie',
  orderbook: 'Order Book',
  tradingpanel: 'Trading Panel',
  marketheatmap: 'Market Heatmap',
  watchlist: 'Watchlist',
  pricealert: 'Price Alert',
  marketoverview: 'Market Overview',
  voicechatwidget: 'Voice Chat Widget',
  audiowaveform: 'Audio Waveform',
  livetranscription: 'Live Transcription',
  callstatus: 'Call Status',
  voiceorb: 'Voice Orb',
  voiceorbnebula: 'Voice Orb - Nebula',
  audiospectrum: 'Audio Spectrum',
  voiceactivity: 'Voice Activity',
  conversationhistory: 'Conversation History',
  audiocontrols: 'Audio Controls',
  linechart: 'Line Chart',
  barchart: 'Bar Chart',
  areachart: 'Area Chart',
  donutchart: 'Donut Chart',
  radarchart: 'Radar Chart',
  scatterplot: 'Scatter Plot',
  progresschart: 'Progress Chart',
  livegauge: 'Live Gauge',
  histogram: 'Histogram',
  multilinechart: 'Multi-Line Chart',
  weatherwidget: 'Weather Widget',
  calendarwidget: 'Calendar Widget',
  timerwidget: 'Timer Widget',
  stopwatchwidget: 'Stopwatch Widget',
  calculatorwidget: 'Calculator Widget',
  musicplayer: 'Music Player',
  photogallery: 'Photo Gallery',
  todolist: 'Todo List',
  notesapp: 'Notes App',
  contactslist: 'Contacts List',
  digitalclock: 'Digital Clock',
  alarmclock: 'Alarm Clock',
  countdown: 'Countdown Timer',
  pomodoro: 'Pomodoro Timer',
  codeeditor: 'Code Editor',
  filemanager: 'File Manager',
  settingspanel: 'Settings Panel',
  userprofile: 'User Profile',
  searchbar: 'Search Bar',
  chatinterface: 'Chat Interface',
  emailclient: 'Email Client',
  eventcalendar: 'Event Calendar',
  kanbanboard: 'Kanban Board',
  ganttchart: 'Gantt Chart',
  datatabls: 'Data Table',
  timelineview: 'Timeline View',
  badgegrid: 'Badge Grid',
  statsdashboard: 'Stats Dashboard',
  feedstream: 'Feed Stream',
  breadcrumbnav: 'Breadcrumb Nav',
  sidemenu: 'Side Menu',
  tabbar: 'Tab Bar',
  megamenu: 'Mega Menu',
  pagination: 'Pagination',
  gamecard: 'Game Card',
  moviecard: 'Movie Card',
  podcastplayer: 'Podcast Player',
  serverstatus: 'Server Status',
  apidocs: 'API Docs',
  codesnippet: 'Code Snippet',
  terminal: 'Terminal',
  databaseview: 'Database View',
  fitnesstracker: 'Fitness Tracker',
  expensetracker: 'Expense Tracker',
  travelplanner: 'Travel Planner',
  recipecard: 'Recipe Card',
  scoreboard: 'Score Board',
  // Additional demos not in categories (extras found during extraction)
  shoppingcart: 'Shopping Cart',
  commentsection: 'Comment Section',
  usercard: 'User Card',
  notificationlist: 'Notification List',
  sharebuttons: 'Share Buttons',
  leaderboard: 'Leaderboard',
  checkoutform: 'Checkout Form',
  ordertracking: 'Order Tracking',
  reviewcard: 'Review Card',
  formwizard: 'Form Wizard',
  searchfilter: 'Search Filter',
  ratinginput: 'Rating Input',
  uploadzone: 'Upload Zone',
  togglegroup: 'Toggle Group',
  workflowbuilder: 'Workflow Builder',
  automationtrigger: 'Automation Triggers',
  workflowtimeline: 'Workflow Timeline',
  workflowsteps: 'Workflow Steps',
  conditionbuilder: 'Condition Builder',
  actionlibrary: 'Action Library',
  workflowtemplate: 'Workflow Templates',
  executionhistory: 'Execution History',
  workflowvariables: 'Workflow Variables',
  integrationpanel: 'Integration Panel',
  workflowscheduler: 'Workflow Scheduler',
  datamapper: 'Data Mapper',
  errorhandling: 'Error Handling',
  workflowversions: 'Workflow Versions',
  notificationcenter: 'Notification Center',
  workflowmetrics: 'Workflow Metrics',
  approvalflow: 'Approval Flow',
  webhooktester: 'Webhook Tester',
  logviewer: 'Log Viewer',
  workflowdebugger: 'Workflow Debugger',
  nodecanvas: 'Node Canvas',
  nodepalette: 'Node Palette',
  nodeinspector: 'Node Inspector',
  nodeminimap: 'Node Minimap',
  nodeconnections: 'Node Connections',
  nodegrouping: 'Node Grouping',
  nodetemplates: 'Node Templates',
  nodeexecution: 'Node Execution',
  nodesearch: 'Node Search',
  nodevalidation: 'Node Validation',
};
